#!/bin/bash

Firstname="TEAM"
Lastname="PLANCK"
echo "$Firstname $Lastname"
echo "$Firstname"
echo "$Lastname"
mkdir TeamPlanck
mkdir Biocomputing && cd Biocomputing
wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.fna 
wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk
wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk
mv wildtype.fna ../TeamPlanck
rmwildtype.gbk.1
grep 'tatatata' wildtype.fna
grep 'tatatata' wildtype.fna>Mutant
clear$$history
ls TeamPlanck && ls Biocomputing
exit
sudo apt-get install figlet
figlet TEAM PLANCK
mkdir Compare
wget https://www.bioinformatics.babraham.ac.uk/training/Introduction%20to%20Unix/unix_intro_data.tar.gz
gunzip unix_intro_data.tar.gz
tar -xvf unix_intro_data.tar.gz
cd seqmonk_genomes
cd saccaromyces cerevisae
cd EF4
cp -t~/compare Mito.dat
mv Mito.dat Mitochondrion
wc -l lane DD P4 TTAGGC L008 R1.fastq.gz
wc -|*.fastq.gz>total.txt
echo "https://github.com/oluwamay/My-FirstBASH/new/main"
